# Generated by Django 5.2.5 on 2025-08-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_date_event_day_rename_title_event_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
