# Generated by Django 5.2.5 on 2025-08-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
